version: '3.4'

services: 
    postgres:
      container_name: backend-db
      image: postgres
      ports:
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: backend
        POSTGRES_PASSWORD: backendandpostgres
        
volumes:
  postgres_data:
